export const SUCCESS = {
  CREATE: {
    STATUS: 201,
    DESCRIPTION: 'CREATED',
  },
  AUTHENTICATED: {
    STATUS: 200,
    DESCRIPTION: 'AUTHENTICATED',
  },
  UPDATE: {
    STATUS: 200,
    DESCRIPTION: 'UPDATED',
  },
  DELETE: {
    STATUS: 202,
    DESCRIPTION: 'ACCEPTED',
  },
};
